import type { INestApplication } from '@nestjs/common';
import type { Prisma } from '@prisma/client';
import { PrismaClient } from '@prisma/client';
import { createTestApp } from './setup';
import { DrugMatchingEngine } from '../src/modules/prescriptions/matching/drug-matching.engine';
import { FulfillmentRequestService } from '../src/modules/fulfillment/fulfillment-request.service';
import { FulfillmentPlanGeneratorService } from '../src/modules/fulfillment/fulfillment-plan-generator.service';
import { INVENTORY_PROVIDER } from '../src/modules/inventory/inventory-provider.interface';
import type { InventoryProvider } from '../src/modules/inventory/inventory-provider.interface';
import { computeAvailableQuantity } from '../src/modules/inventory/inventory-calculations';
import { normalizeSearchInput } from '../src/modules/dic/normalization';

const prisma = new PrismaClient();
const TAG = '9EFULFILL5';

/** Mirrors Step 4's fixture convention — the real DrugCandidateGenerator
 *  only ever looks at normalized/search fields, never raw nameEn. */
function fixtureDrugData(materialNo: string, nameEn: string, extra: Partial<Prisma.DrugCreateInput> = {}) {
  return {
    materialNo,
    nameEn,
    active: true,
    normalizedTradeNameEnglish: normalizeSearchInput(nameEn),
    searchNameEnglish: normalizeSearchInput(nameEn),
    combinedSearchText: normalizeSearchInput(nameEn),
    ...extra,
  };
}

/**
 * Phase 6 Step 5 — FulfillmentPlanGeneratorService: Stage 4 (live
 * inventory coverage check via InventoryProvider) + Stage 5 (weighted
 * ranking) + plan persistence. MockInventoryProvider's stock numbers
 * are deterministic-per-(branchId,drugId) but not chooseable up front
 * (branch ids are generated by Prisma), so most scenarios here use
 * requiredQuantity=0 ("any stock, even none, satisfies a zero
 * requirement" — already the pure computeBranchCoverage behaviour,
 * unit-tested separately) to force a guaranteed AVAILABLE outcome
 * without depending on the mock's random seed, and requiredQuantity=
 * 999999 to force a guaranteed non-AVAILABLE outcome. The one test that
 * genuinely needs two branches to differ in stock (PG-6, the "nearest
 * is not always best" case) queries the live provider after creation to
 * learn its real numbers, matching how a real caller would behave.
 */
describe('FulfillmentPlanGeneratorService (e2e)', () => {
  let app: INestApplication;
  let engine: DrugMatchingEngine;
  let requestService: FulfillmentRequestService;
  let generator: FulfillmentPlanGeneratorService;
  let inventoryProvider: InventoryProvider;
  let uploaderId: string;
  let regionId: string;

  async function cleanup() {
    await prisma.fulfillmentPlanItem.deleteMany({
      where: { fulfillmentPlanBranch: { fulfillmentPlan: { fulfillmentRequest: { prescription: { note: { contains: TAG } } } } } },
    });
    await prisma.fulfillmentPlanBranch.deleteMany({
      where: { fulfillmentPlan: { fulfillmentRequest: { prescription: { note: { contains: TAG } } } } },
    });
    await prisma.fulfillmentPlan.deleteMany({ where: { fulfillmentRequest: { prescription: { note: { contains: TAG } } } } });
    await prisma.fulfillmentRequestItem.deleteMany({
      where: { fulfillmentRequest: { prescription: { note: { contains: TAG } } } },
    });
    await prisma.fulfillmentRequest.deleteMany({ where: { prescription: { note: { contains: TAG } } } });
    await prisma.searchLocation.deleteMany({ where: { addressText: { contains: TAG } } });
    await prisma.branch.deleteMany({ where: { code: { startsWith: `${TAG}-` } } });
    await prisma.drug.deleteMany({ where: { materialNo: { startsWith: TAG } } });
    await prisma.prescription.deleteMany({ where: { note: { contains: TAG } } });
    await prisma.city.deleteMany({ where: { code: { startsWith: TAG } } });
    await prisma.region.deleteMany({ where: { code: { startsWith: TAG } } });
    await prisma.user.deleteMany({ where: { email: { contains: TAG.toLowerCase() } } });
  }

  async function seedConfirmedLines(drugIds: string[]) {
    const rx = await prisma.prescription.create({
      data: {
        number: `PRX-${TAG}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        status: 'EXTRACTING',
        uploadedById: uploaderId,
        note: `${TAG} fixture`,
      },
    });
    const page = await prisma.prescriptionPage.create({
      data: { prescriptionId: rx.id, pageNumber: 1, originalStorageKey: `${TAG}/${rx.id}.jpg`, processingStatus: 'COMPLETED' },
    });
    const ocrRun = await prisma.prescriptionOcrRun.create({
      data: {
        prescriptionPageId: page.id,
        runNumber: 1,
        providerName: 'test-fixture',
        trigger: 'initial',
        settingsSnapshotJson: {},
        status: 'COMPLETED',
      },
    });
    const lineIds: string[] = [];
    let blockIndex = 0;
    for (const drugId of drugIds) {
      const drug = await prisma.drug.findUniqueOrThrow({ where: { id: drugId } });
      const rawText = `${drug.nameEn} 500 mg`;
      await prisma.oCRTextBlock.create({
        data: {
          prescriptionPageId: page.id,
          ocrRunId: ocrRun.id,
          rawText,
          normalizedText: normalizeSearchInput(rawText),
          language: 'en',
          ocrConfidence: 0.95,
          lineNumber: blockIndex,
          blockIndex,
        },
      });
      blockIndex++;
    }
    await prisma.prescriptionPage.update({ where: { id: page.id }, data: { currentOcrRunId: ocrRun.id } });
    await engine.run(rx.id);

    for (const drugId of drugIds) {
      const drug = await prisma.drug.findUniqueOrThrow({ where: { id: drugId } });
      const line = await prisma.prescriptionMedicationLine.findFirstOrThrow({
        where: { prescriptionId: rx.id, rawText: { contains: drug.nameEn } },
      });
      const candidate = await prisma.prescriptionDrugCandidate.findFirstOrThrow({
        where: { medicationLineId: line.id },
        orderBy: { rank: 'asc' },
      });
      const confirmedLine = await prisma.prescriptionMedicationLine.update({
        where: { id: line.id },
        data: {
          matchingStatus: 'CONFIRMED',
          selectedDrugId: drugId,
          selectedCandidateId: candidate.id,
          reviewRequired: false,
        },
      });
      lineIds.push(confirmedLine.id);
    }
    return { prescriptionId: rx.id, lineIds };
  }

  beforeAll(async () => {
    app = await createTestApp();
    engine = app.get(DrugMatchingEngine);
    requestService = app.get(FulfillmentRequestService);
    generator = app.get(FulfillmentPlanGeneratorService);
    inventoryProvider = app.get(INVENTORY_PROVIDER);
    await cleanup();

    const uploader = await prisma.user.create({
      data: {
        email: `uploader.${TAG.toLowerCase()}@milaserv360.test`,
        passwordHash: 'x',
        nameAr: 'رافع',
        nameEn: `Uploader ${TAG}`,
      },
    });
    uploaderId = uploader.id;

    const region = await prisma.region.create({
      data: { code: `${TAG}-R1`, nameEn: 'Test Region', nameAr: 'منطقة اختبار' },
    });
    regionId = region.id;
  });

  afterAll(async () => {
    try {
      await cleanup();
    } finally {
      await prisma.$disconnect();
      await app.close();
    }
  });

  // Each test gets its own city — Stage 1's city filter then isolates
  // it from every other test's branches, so exact-length plan
  // assertions don't pick up leftovers left behind by earlier tests in
  // this same describe block (afterAll is the only cleanup point).
  let citySuffix = 0;
  async function makeCity(): Promise<string> {
    citySuffix++;
    const city = await prisma.city.create({
      data: {
        code: `${TAG}-C${citySuffix}`,
        regionId,
        nameEn: `Plan Generator Test City ${citySuffix}`,
        nameAr: `مدينة اختبار التخطيط ${citySuffix}`,
        normalizedNameEn: `plan generator test city ${citySuffix}`,
        normalizedNameAr: `مدينة اختبار التخطيط ${citySuffix}`,
        latitude: 24.7,
        longitude: 46.7,
      },
    });
    return city.id;
  }

  async function makeBranch(cityId: string, suffix: string, lat: number, lng: number) {
    return prisma.branch.create({
      data: {
        code: `${TAG}-${suffix}`,
        nameAr: `فرع ${suffix}`,
        nameEn: `Branch ${suffix}`,
        locationCityId: cityId,
        status: 'ACTIVE',
        prescriptionFulfillmentEnabled: true,
        latitude: lat,
        longitude: lng,
      },
    });
  }

  it('PG-1 no eligible branches at all produces one explanatory NO_SAFE_PLAN row and NO_OPTIONS_FOUND status', async () => {
    const cityId = await makeCity();
    const drug = await prisma.drug.create({ data: fixtureDrugData(`${TAG}1`, `${TAG} DrugPG1`) });
    const { prescriptionId, lineIds } = await seedConfirmedLines([drug.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-1`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });

    const plans = await generator.generate(request.id);

    expect(plans).toHaveLength(1);
    expect(plans[0]!.planType).toBe('NO_SAFE_PLAN');
    expect(plans[0]!.branchCount).toBe(0);
    expect(plans[0]!.completeCoverage).toBe(false);
    expect((plans[0]!.explanationJson as { reason: string }).reason).toMatch(/No eligible branches/);

    const updated = await prisma.fulfillmentRequest.findUniqueOrThrow({ where: { id: request.id } });
    expect(updated.status).toBe('NO_OPTIONS_FOUND');
  });

  it('PG-2 an eligible branch whose stock can never satisfy the requirement produces NO_SAFE_PLAN, not a false positive', async () => {
    const cityId = await makeCity();
    const drug = await prisma.drug.create({ data: fixtureDrugData(`${TAG}2`, `${TAG} DrugPG2`) });
    await makeBranch(cityId, 'PG2', 24.7, 46.7);
    const { prescriptionId, lineIds } = await seedConfirmedLines([drug.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-2`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });
    // No branch ever stocks 999999 units — guarantees non-AVAILABLE
    // regardless of the mock provider's actual (random-seeded) numbers.
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id },
      data: { requiredQuantity: 999999 },
    });

    const plans = await generator.generate(request.id);

    expect(plans).toHaveLength(1);
    expect(plans[0]!.planType).toBe('NO_SAFE_PLAN');
    const updated = await prisma.fulfillmentRequest.findUniqueOrThrow({ where: { id: request.id } });
    expect(updated.status).toBe('NO_OPTIONS_FOUND');
  });

  it('PG-3 a single eligible branch with complete coverage is persisted as a ranked SINGLE_BRANCH plan, never auto-selected', async () => {
    const cityId = await makeCity();
    const drug = await prisma.drug.create({ data: fixtureDrugData(`${TAG}3`, `${TAG} DrugPG3`) });
    const branch = await makeBranch(cityId, 'PG3', 24.7, 46.7);
    const { prescriptionId, lineIds } = await seedConfirmedLines([drug.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-3`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });
    // requiredQuantity=0 — "any stock, even none, satisfies zero" is the
    // pure computeBranchCoverage rule (already unit-tested); it lets
    // this orchestration test not depend on the mock's random seed.
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id },
      data: { requiredQuantity: 0 },
    });

    const plans = await generator.generate(request.id);

    expect(plans).toHaveLength(1);
    expect(plans[0]!.planType).toBe('SINGLE_BRANCH');
    expect(plans[0]!.rank).toBe(1);
    expect(plans[0]!.completeCoverage).toBe(true);
    expect(plans[0]!.selected).toBe(false);
    expect(plans[0]!.branches).toHaveLength(1);
    expect(plans[0]!.branches[0]!.branchId).toBe(branch.id);
    expect(plans[0]!.branches[0]!.items).toHaveLength(1);
    expect(plans[0]!.branches[0]!.items[0]!.availabilityStatus).toBe('AVAILABLE');

    const updated = await prisma.fulfillmentRequest.findUniqueOrThrow({ where: { id: request.id } });
    expect(updated.status).toBe('OPTIONS_FOUND');
  });

  it('PG-4 two complete-coverage branches are both ranked, with the nearer one first', async () => {
    const cityId = await makeCity();
    const drug = await prisma.drug.create({ data: fixtureDrugData(`${TAG}4`, `${TAG} DrugPG4`) });
    const near = await makeBranch(cityId, 'PG4-NEAR', 24.701, 46.701); // ~0.15km
    const far = await makeBranch(cityId, 'PG4-FAR', 24.85, 46.85); // ~22km-ish, still complete
    const { prescriptionId, lineIds } = await seedConfirmedLines([drug.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-4`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id },
      data: { requiredQuantity: 0 },
    });

    const plans = await generator.generate(request.id);

    expect(plans).toHaveLength(2);
    expect(plans.every((p) => p.completeCoverage)).toBe(true);
    expect(plans[0]!.rank).toBe(1);
    expect(plans[1]!.rank).toBe(2);
    expect(plans[0]!.branches[0]!.branchId).toBe(near.id);
    expect(plans[1]!.branches[0]!.branchId).toBe(far.id);
    expect(plans[0]!.totalScore).toBeGreaterThan(plans[1]!.totalScore);
  });

  it('PG-5 two branches each covering a different half of the request are combined into one SPLIT_BRANCH plan', async () => {
    const cityId = await makeCity();
    const drugA = await prisma.drug.create({ data: fixtureDrugData(`${TAG}5A`, `${TAG} DrugPG5A`) });
    const drugB = await prisma.drug.create({ data: fixtureDrugData(`${TAG}5B`, `${TAG} DrugPG5B`) });

    async function available(branchId: string, drugId: string): Promise<number> {
      const rows = await inventoryProvider.getBranchInventory(branchId, [drugId]);
      const row = rows[0];
      return (
        computeAvailableQuantity(row?.onHandQuantity ?? null, row?.reservedQuantity ?? null, row?.blockedQuantity ?? null, row?.damagedQuantity ?? null) ?? 0
      );
    }

    // Retry with fresh branch ids until we get a "crossing" pattern —
    // one branch strictly better stocked for drug A, the other strictly
    // better stocked for drug B — so a required quantity can be chosen
    // that only the better-stocked branch meets for each drug,
    // guaranteeing a genuine two-branch split regardless of the mock
    // provider's actual (random-seeded) numbers.
    let aProvider: Awaited<ReturnType<typeof makeBranch>> | null = null;
    let bProvider: Awaited<ReturnType<typeof makeBranch>> | null = null;
    let requiredA = 0;
    let requiredB = 0;
    for (let attempt = 0; attempt < 8 && !aProvider; attempt++) {
      const x = await makeBranch(cityId, `PG5-X${attempt}`, 24.7, 46.7);
      const y = await makeBranch(cityId, `PG5-Y${attempt}`, 24.71, 46.71);
      const [xA, yA, xB, yB] = await Promise.all([
        available(x.id, drugA.id),
        available(y.id, drugA.id),
        available(x.id, drugB.id),
        available(y.id, drugB.id),
      ]);
      if (xA > yA && yB > xB) {
        aProvider = x;
        bProvider = y;
        requiredA = yA + 1;
        requiredB = xB + 1;
      } else if (yA > xA && xB > yB) {
        aProvider = y;
        bProvider = x;
        requiredA = xA + 1;
        requiredB = yB + 1;
      } else {
        await prisma.branch.deleteMany({ where: { id: { in: [x.id, y.id] } } });
      }
    }
    if (!aProvider || !bProvider) {
      throw new Error('Could not find a crossing stock pattern after 8 attempts');
    }

    const { prescriptionId, lineIds } = await seedConfirmedLines([drugA.id, drugB.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-5`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id, drugId: drugA.id },
      data: { requiredQuantity: requiredA },
    });
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id, drugId: drugB.id },
      data: { requiredQuantity: requiredB },
    });

    const plans = await generator.generate(request.id);

    expect(plans).toHaveLength(1);
    expect(plans[0]!.planType).toBe('SPLIT_BRANCH');
    expect(plans[0]!.completeCoverage).toBe(true);
    expect(plans[0]!.branches).toHaveLength(2);
    const branchIds = plans[0]!.branches.map((b) => b.branchId).sort();
    expect(branchIds).toEqual([aProvider.id, bProvider.id].sort());

    const updated = await prisma.fulfillmentRequest.findUniqueOrThrow({ where: { id: request.id } });
    expect(updated.status).toBe('OPTIONS_FOUND');
  });

  it('PG-6 a nearer branch missing part of the order is not offered as a complete option when a farther branch has everything', async () => {
    const cityId = await makeCity();
    const drug = await prisma.drug.create({ data: fixtureDrugData(`${TAG}6`, `${TAG} DrugPG6`) });

    // Create branch pairs and keep retrying with fresh ids until the
    // mock provider's deterministic-per-id hash gives us one branch
    // with strictly more stock than the other for this drug — the
    // higher-stock branch becomes "far" (complete), the lower-stock
    // branch becomes "near" (incomplete), replaying the brief's
    // "nearest is not always best" example without depending on a
    // specific random seed.
    let completeBranch: Awaited<ReturnType<typeof makeBranch>> | null = null;
    let incompleteBranch: Awaited<ReturnType<typeof makeBranch>> | null = null;
    let requiredQuantity = 0;
    for (let attempt = 0; attempt < 8 && !completeBranch; attempt++) {
      const x = await makeBranch(cityId, `PG6-X${attempt}`, 24.7, 46.7);
      const y = await makeBranch(cityId, `PG6-Y${attempt}`, 24.7, 46.7);
      const rowsX = await inventoryProvider.getBranchInventory(x.id, [drug.id]);
      const rowsY = await inventoryProvider.getBranchInventory(y.id, [drug.id]);
      const availX =
        computeAvailableQuantity(
          rowsX[0]?.onHandQuantity ?? null,
          rowsX[0]?.reservedQuantity ?? null,
          rowsX[0]?.blockedQuantity ?? null,
          rowsX[0]?.damagedQuantity ?? null,
        ) ?? 0;
      const availY =
        computeAvailableQuantity(
          rowsY[0]?.onHandQuantity ?? null,
          rowsY[0]?.reservedQuantity ?? null,
          rowsY[0]?.blockedQuantity ?? null,
          rowsY[0]?.damagedQuantity ?? null,
        ) ?? 0;

      if (availX > availY) {
        completeBranch = x;
        incompleteBranch = y;
        requiredQuantity = availY + 1;
      } else if (availY > availX) {
        completeBranch = y;
        incompleteBranch = x;
        requiredQuantity = availX + 1;
      } else {
        await prisma.branch.deleteMany({ where: { id: { in: [x.id, y.id] } } });
      }
    }
    if (!completeBranch || !incompleteBranch) {
      throw new Error('Could not find two branches with differing mock stock after 8 attempts');
    }

    // Farther, but has enough stock; nearer, but doesn't.
    await prisma.branch.update({ where: { id: completeBranch.id }, data: { latitude: 24.85, longitude: 46.85 } });
    await prisma.branch.update({ where: { id: incompleteBranch.id }, data: { latitude: 24.701, longitude: 46.701 } });

    const { prescriptionId, lineIds } = await seedConfirmedLines([drug.id]);
    const location = await requestService.createSearchLocation({
      cityId,
      latitude: 24.7,
      longitude: 46.7,
      sourceType: 'MAP_PIN',
      addressText: `${TAG} PG-6`,
    });
    const request = await requestService.createRequest({ prescriptionId, medicationLineIds: lineIds, searchLocationId: location.id });
    await prisma.fulfillmentRequestItem.updateMany({
      where: { fulfillmentRequestId: request.id },
      data: { requiredQuantity },
    });

    const plans = await generator.generate(request.id);

    const singleBranchPlans = plans.filter((p) => p.planType === 'SINGLE_BRANCH');
    expect(singleBranchPlans.some((p) => p.branches[0]!.branchId === completeBranch!.id)).toBe(true);
    expect(singleBranchPlans.some((p) => p.branches[0]!.branchId === incompleteBranch!.id)).toBe(false);
  });
});
